{
	"schemaErrors": {
		"general": "The request body is invalid.",
		"location": "Location must contain at least 2 characters.",
		"targetDateTimestamp": "The target date must be a positive number or can be omitted.",
		"articleType": "The article type is invalid. Allowed types are: 'factual' or 'bulvar'.",
		"language": "Language must be either 'sk' or 'en'.",
		"missingBody": "The request body is missing.",
		"limitMax10": "The limit must be a positive number less than 10.",
		"typeErrors": {
			"string": "Value must be a string.",
			"int": "Value must be an integer.",
			"number": "Value must be a number.",
			"boolean": "Value must be boolean.",
			"array": "Value must be an array.",
			"object": "Value must be an object.",
			"null": "Value must be null.",
			"positive": "Value must be a positive number.",
			"nonNegative": "Value must be a non-negative number."
		}
	},
	"errorMessages": {
		"weatherClient": {
			"weatherFetch": "An error occurred while fetching the forecast data.",
			"weatherParse": "An error occurred while working with the forecast data.",
			"locationFetch": "An error occurred while fetching the location data.",
			"locationParse": "An error occurred while working with the location data.",
			"locationZeroMatch": "The location data for such place was not found."
		},
		"LLMClient": {
			"fetch": "It was not possible to generate article due to internal network error",
			"parse": "It was not possible to generate article due to incositent data"
		}
	},
	"weatherServiceGeneralMessages": {
		"unknownErrorDuringIntialization": "An unknown error occurred during the initialization of the weather service.",
		"rateLimitExceeded": "The rate limit for the weather service has been exceeded. Please try again later."
	},
	"test": {
		"test1": "Test1 en",
		"test2": "Test2 en",
		"innerTest": {
			"innerTest1": "InnerTest1 en",
			"innerTest2": "InnerTest2 en"
		},
		"null": null,
		"number": 123
	}
}
